### ISSUE TITLE
Add filter for new parties only

### ISSUE THREAD

**Issue by dkhamsing** [genadyo/WWDC#64]
With the blue dots :large_blue_circle: 
:smile:

**Comment by genadyo** [comment]
You can easily scan it, why do you need filters :)?

**Comment by dkhamsing** [comment]
Lazy? haha

**Comment by genadyo** [comment]
It's open source, you're welcome to help.

**Comment by dkhamsing** [comment]
Yeah for sure.. I think I could get started but without all the keys, may need your help to finish..
